package com.exament.apistack.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.Pattern;

@Entity
public class User
{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Column(name = "image")
    //@ApiModelProperty(notes = "Autogenerated User id", required = true)
    private String image;
    @Column(name = "name")
    //@ApiModelProperty(notes = "User name")
    private String name;
    @Column(name = "email")
    @Email(regexp = "[a-z0-9._%+-]+@[a-z0-9.-]+\\\\.[a-z]{2,3}", flags = Pattern.Flag.CASE_INSENSITIVE)
    //@ApiModelProperty(notes = "User email")
    private String email;
    @Column(name = "gender")
    //@ApiModelProperty(notes = "User gender")
    private String gender;
    @Column(name = "estatus")
    //@ApiModelProperty(notes = "User estatus")
    private Long estatus;

    @Lob
    private byte[] content;

    public User()
    { }

    public User(Long id, String image, String name, String email, String gender, Long estatus)
    {
        this.id = id;
        this.image = image;
        this.name = name;
        this.email = email;
        this.gender = gender;
        this.estatus = estatus;
    }

    public String getImage()
    {
        return image;
    }

    public void setImage(String image)
    {
        this.image = image;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public String getGender()
    {
        return gender;
    }

    public void setGender(String gender)
    {
        this.gender = gender;
    }

    public Long getEstatus()
    {
        return estatus;
    }

    public void setEstatus(Long estatus)
    {
        this.estatus = estatus;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public Long getId()
    {
        return id;
    }

    @JsonIgnore
    public byte[] getContent() {
        return content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }
}
